name: google_fonts
description: Compatibility shim for google_fonts with Flutter 3.27+
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  path_provider: any

flutter:
